### ISSUE TITLE
How I can run flow with different policies (edit, change password)

### ISSUE THREAD

**Issue by brucemax** [Azure-Samples/active-directory-b2c-android-native-nodejs-webapi#3]
When I logged in and run flow with above policies I get just credential object and have not screen for edit info or change password

**Comment by gsacavdm** [comment]
Checkout the [edit-profile](https://github.com/Azure-Samples/active-directory-b2c-android-native-nodejs-webapi/tree/edit-profile) branch which shows how to do this. You need to a separate OAuthManager with a different "user", making sure to deleteCredentials for that other "user" every time.

**IMPORTANT NOTE**:  If at all possible, you should try the approach in our [other Android sample which uses AppAuth](https://github.com/Azure-Samples/active-directory-android-native-appauth-b2c) and system web views, especially if you want to support Google Sign-in which won't work with the embedded web view approach in this sample.
